name: ClanPlugin
version: 1.0-SNAPSHOT
api-version: '1.21.1'
author: EntixOG
main: io.entix.ClanPlugin
description: Clan plugin with various features for a comprehensive experience.
website: https://github.com/EntixOG
