name: ClanPlugin
version: 1.0-SNAPSHOT
api-version: '1.21.1'
author: EntixOG
main: io.entix.ClanPlugin
description: Clan plugin with various features for a comprehensive experience.
website: https://github.com/EntixOG
libraries:
  - org.mongodb:mongodb-driver-sync:4.11.1
  - eu.koboo:en2do:3.1.9
